### ISSUE TITLE
Error messages when repository loading fails are not sufficient

### ISSUE THREAD

**Issue by matthiasbeyer** [science-computing/butido#27] opened 2021-11-18 21:43 UTC
## What

* [x] Bug
* [ ] Feature Request
* [ ] Question
* [ ] Other

When loading the repository fails, the error message is not verbose enough (does not tell where the loading failed, for example).

**Comment by christophprokop** [comment] 2022-11-30 17:25
duplicate of #47

**Closed by christophprokop** 2022-11-30 17:25 UTC
Labels: duplicate
